name: aqualife
description: AquaLife

version: 1.2.34+34

environment:
  sdk: ">=3.1.0 <4.0.0"

publish_to: none

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_localizations:
    sdk: flutter
  flutter_mobx: any
  flutter_native_timezone: any
  flutter_svg: any
  hive: any
  intl: any
  mobx: any
  package_info_plus: any
  path_provider: any
  timezone: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  hive_generator: any
  mobx_codegen: any

flutter_icons:
  ios: true
  android: true
  image_path: assets/dev/ios_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  main_locale: en
  enabled: true

flutter_native_splash:
  background_image: "assets/images/background.png"
